namespace Vidly.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class Insertdate : DbMigration
    {
        public override void Up()
        {
            Sql("delete from Customers");
            Sql("dbcc checkident('Customers', reseed, 0)");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Aayush Das', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Aayushka Shrestha', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Naman Shrestha', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Riyas Thapa', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Samira Laxmi Shrestha', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Trisa Basnet', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sayujya Shrestha', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Isaya Nagarkoti', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Rikesh Nepal', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Utkrista Karki', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Subisha Giri', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Digvijay Raj Khadka', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Aarshu Shrestha', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sanisha Lama', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Abhinav Shrestha', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Anmol Dhungana', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Aayush Dhungel', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Niraj Dhami', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Prabhi Dhital', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Prama Shrestha', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Prasiddha Shumsher Thapa', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Riya Shrestha', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sambriddhi Bumjung', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Samriddhi Tamang', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sanjan Sulu', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Kritika Khatri', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sikshya Negi', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Aslesha Parajuli', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Mikesh Apagain', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Alisha Guragain', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Angel Shrestha', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Diben Neupane', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Diyash Nepal', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ishu Dhungel', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Jesika Joshi', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Megha Lamichhane', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Kushal Raj Parajuli', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Kusum Majhi', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Suraj Lama', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Triza Duwal ', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sherya Kafle ', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Aliza Khadka', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bedanta Joshi', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Saugat Karki ', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Nabin K.C.', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Norsang Sherpa', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Rashmi Karki', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Rashmita Tamang', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Reshma Majhi', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Samir Chaulagai', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Saugat Karki', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Saurav Shrestha', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Shersang Sherpa', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Arogya Shrestha', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bishesh Koirala', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Kanchan Thapa', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Leeyaz Shrestha', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Purnima Karki', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Roshni Maghi', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Milan Gautam ', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sumanta Khanal', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ronish Shrestha', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Mikal Apagain ', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Samrat Thapa', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Shreyasi Shrestha', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Shrishma Tamang', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Shrutika Neupane', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Aditi Shrestha', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Angelina Shrestha', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Binisha Lama', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bisesh Thapa', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Dipsan Upreti', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Jesika Das', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Luvkush Singh', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Pema Sherpa', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Prashiksha Niraula', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ronik Nepal ', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Saugat Magar', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Amrita Kumari ', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bikesh Lama', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sandesh Lama', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Aarushi Shrestha', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Aryan Thapa', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Dristika Sakha', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Rishta Thapa', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Roshan Karki', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sapana Kumari Dhami', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bibek  Lama', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Smarika Karki', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Suprina Gurung', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Trishna Basnet', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Asmita Pakhrin', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Piyush Das', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Salama Rai', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Shabnam Dhakal', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Kamana Apagai ', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ashok Shrestha', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Grishma Tamang', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Aryan Tiwari ', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Samana Tamang', 1, 2,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Anu Shrestha', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Aayush Karki', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Pemba Shrepa', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Pujan Adhikari', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Subash Shrestha', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Pranjal Thapa', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bini Ghishing', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Pooja Adhikari', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Rojina Karki', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bishal Lama', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Chandri Maya Karki', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sumina Lama', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Regina Rai', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Suresh Prasad Das', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Jina Shrestha', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Chakra Shrestha', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Rakesh Thapa', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Samin Krishna Shrestha', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Samin Krishna Shrestha', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Shova K.C.', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Dipak Nagarkoti ', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ramchandra Nepal', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Uddhav Karki', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Lekh Raj Giri', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bikash Khadka', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Urvashi Shrestha', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bhim Lama', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Raj Kumar Shrestha', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Amar Dhungana', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Basanta Raj Dhungel', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Krishna Bahadur Dhami', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bhim Kanta Dhital', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Prakash Shrestha', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bhuwan Thapa', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Shova Shrestha', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Chye Dorje Tamang', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Kumar Tamang', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Jeevan Sulu', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Dhan Singh Khatri', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Lalit Negi', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('gaitri Pd. Parajuli', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Kalyan Apagain', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Leela Guagain', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Prakash Shrestha', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Dipak Neupane', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Deepak Nepal', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Basanta Raj Dhungel', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Prem Kamal Joshi', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('pradeesh Lamichhane', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Madhav Parajuli', 1, 3,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Kumar Majhi', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Amir Lama', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Saral Gopal Maharjan', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ram Krishna Kafle', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Arjun Khadka', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Kundan Joshi', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Maiya Karki', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Birkha Bahadur K.C.', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Phurba Yangtse Sherpa', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Maiya Karki', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Maite Pakhrin', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ramesh Majhi', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Dilip Chaulagain', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Maiya Karki', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Shyam Shrestha', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Phurba Yangtse Sherpa', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Rajendra Shrestha', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Balaram Koirala', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Nauraj Thapa', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Jayendra Kumar Shrestha', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Uddhav Karki', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ramesh Majhi', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bimala Gautam ', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Pramod Poudel ', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Gobardhan Shrestha ', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Kalyan Apagain', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Saroj Thapa', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Chakra Shrestha', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ganesh Tamang', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Pashupati Neupane', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Raj Kumar Shrestha', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Prakash Shrestha', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Amar Lama', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Saroj Thapa', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ishwori Upreti', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Suresh Prasad Das', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Pratigya Dhungel Singh', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Phurba Yangtse Sherpa', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Deepak Mani Niraula', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ramchandra Nepal', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sanu Magar', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Binod Chaudhary', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Buddha Lama', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sonam Lama', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Rajendra Shrestha', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Anita Shrestha', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Om Prakash Sakha', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sabina Thapa', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Maiya Karki', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Krishna Bahadur Dhami', 0, 4,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sunmaya Lama', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Uddhav Karki', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Santosh Gurung', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Tej Bahadur Basnet', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Naita Tamang', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Suresh Prasad Das', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bikash Rai', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ratna Dhakal', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Kalyan Apagain', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Anita Shrestha', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Ganesh Tamang', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Jeevan Tiwari', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sagar Tamang', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Anita Shrestha', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Arjun Karki', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Phurba Yangtse Sherpa', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Pushpa Hari  Adhikari', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Navaraj Shrestha', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Bhupeshwor Thapa', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Dipak Ghishing', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Pushpa Hari  Adhikari', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Maiya Karki', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Amar Lama', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Dhan Kumar Karki', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Sunmaya Lama', 0, 1,'1900-01-01 00:00:00')");
            Sql("INSERT INTO [dbo].[Customers] ([Name], [IsSubscribedTONewsLetter], [MembershipTypeId], [DateofBirth]) VALUES ('Santa Ram Rai', 0, 1,'1900-01-01 00:00:00')");
        }

        public override void Down()
        {
        }
    }
}
